version: '3.8'

services:
  api:
    build: ./back
    container_name: api
    ports:
      - "3000:3000"
    volumes:
        - ./back:/app

  front:
    build: ./front
    container_name: front
    ports:
      - "5173:5173"
    volumes:
        - ./front:/app