name: Demo Workflows

on:
  push:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      api:
        image: node:18-slim
        options: --name api
        ports:
          - 3000:3000
      front:
        image: node:lts-alpine
        options: --name front
        ports:
          - 8080:80

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '18'

      - name: Install dependencies (API)
        working-directory: ./back
        run: npm i

      - name: Install dependencies (Front)
        working-directory: ./front
        run: npm i

      - name: Run API
        working-directory: ./back
        run: npm start

      - name: Run tests
        run: npm test

      - name: Build Frontend
        working-directory: ./front
        run: npm run build